### ISSUE TITLE
Any Ideas how to bridge or Sync ID's

### ISSUE THREAD

**Issue by Bl00d-B0b** [hencou/esphome_components#24]
Hello,

I have rgb_cct Wall switch ID:0x02CB and rgb_cct Remote Control ID:0x1F83. Both paired and manages same groups of Mi LED's. 

Is it possible to configure like a "bridge" button, which can see ON/OFF if any of  my Switch or remote control ON/OFF light???

Maybe another implementation? Like Syncing buttons... Just try to think... Any Ideas?

Ed

**Comment by Bl00d-B0b** [comment]
hello,

thanks, i'll try

**Comment by Bl00d-B0b** [comment]
Is it possible to implement within same esphome, without homeassistant. just in .yaml file.

**Comment by hencou** [comment]
I don't know how, maybe there is a ESPhome component enabling communication between them? Otherwise an MQTT broker between them can maybe an option.

**Comment by hencou** [comment]
Closed: implementing a "bridge" is more ESPhome or HomeAssistant related.
