### ISSUE TITLE
esp32 compatible?

### ISSUE THREAD

**Issue by jetflux** [hencou/esphome_components#8]
Hi, excuse me for asking here, but can I use this with esp32? or is it only esp8266.

**Comment by hencou** [comment]
Hi Jetflux,

I've never tried this at myself, but I expect that this will work. Do you experience a specific error?

**Comment by shbatm** [comment]
Yes, it is working for me on a ESP32 D1 Mini board.

**Comment by hencou** [comment]
Great! I will close the ticket then.

**Comment by jetflux** [comment]
Hi!, i tried compile it and it works. but get small error:
``
 .platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c: In function 'spiTransferBytesNL':
``

 ``
.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:922:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_out8 = &result[c_longs-1];
``

``
.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:923:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_data8 = &last_data;
                                        ^
``

maybe nothing to worry about? , I will try to upload and wire it to a esp32 this weekend.

**Comment by hencou** [comment]
Most of times you can ignore these kind of warnings. Its a warning coming from the SPI ESP32 library it seems.

**Comment by poudenes** [comment]
I have a AZ Delivery D1 R32 board. But what I try on pins its not working for me at all.
With a Wemos D1 it is working, but changed because of bigger ram. Now I can add all my 36 bulbs in config.

Can someone help me with the right pinout to let this work?
